-- Gap-fill: the two remaining "major" gaps from the SymptoTrack parity
-- review — an in-app notification feed (previously the only notification
-- channel was outbound email, and only for appointments/doses) and
-- doctor<->patient messaging (didn't exist at all).
--
-- Notifications are generated by security-definer triggers, not application
-- code — the same pattern this schema already uses for handle_new_user.
-- This keeps "who gets notified when" as a single source of truth in the
-- database rather than scattered across every server action that touches
-- these tables.

create type public.notification_type as enum (
  'appointment_booked',
  'appointment_cancelled',
  'appointment_completed',
  'prescription_created',
  'medical_record_added',
  'report_uploaded',
  'report_reviewed',
  'report_critical',
  'message_received',
  'account_approved',
  'bill_created'
);

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  type public.notification_type not null,
  title text not null,
  body text,
  link text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index idx_notifications_user on public.notifications (user_id, created_at desc);

alter table public.notifications enable row level security;

create policy "notifications_select_own" on public.notifications
  for select using (user_id = auth.uid());

create policy "notifications_update_own" on public.notifications
  for update using (user_id = auth.uid());

-- Deliberately no insert policy — every row is written by a security-definer
-- trigger function below (which bypasses RLS via its owning role, same as
-- handle_new_user), never directly by an authenticated client. Otherwise any
-- signed-in user could insert a notification against any other user_id.

create or replace function public.notify(
  p_user_id uuid,
  p_type public.notification_type,
  p_title text,
  p_body text,
  p_link text
) returns void
language sql
security definer
set search_path = public
as $$
  insert into public.notifications (user_id, type, title, body, link)
  values (p_user_id, p_type, p_title, p_body, p_link);
$$;

-- appointments: notify the doctor on booking; notify both parties on
-- cancellation (there's no "changed_by" column to know who acted, so both
-- get notified — the actor just sees their own action reflected back).
create or replace function public.on_appointment_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  patient_name text;
  doctor_name text;
  when_text text;
begin
  select full_name into patient_name from public.profiles where id = new.patient_id;
  select full_name into doctor_name from public.profiles where id = new.doctor_id;
  when_text := to_char(new.appointment_at, 'DD Mon YYYY, HH12:MI AM');

  if tg_op = 'INSERT' then
    perform public.notify(
      new.doctor_id, 'appointment_booked', 'New appointment booked',
      coalesce(patient_name, 'A patient') || ' booked an appointment for ' || when_text,
      '/doctor/appointments'
    );
  elsif tg_op = 'UPDATE' and new.status = 'cancelled' and old.status <> 'cancelled' then
    perform public.notify(
      new.patient_id, 'appointment_cancelled', 'Appointment cancelled',
      'Your appointment with Dr. ' || coalesce(doctor_name, '') || ' on ' || when_text || ' was cancelled.',
      '/patient/appointments'
    );
    perform public.notify(
      new.doctor_id, 'appointment_cancelled', 'Appointment cancelled',
      'Appointment with ' || coalesce(patient_name, '') || ' on ' || when_text || ' was cancelled.',
      '/doctor/appointments'
    );
  elsif tg_op = 'UPDATE' and new.status = 'completed' and old.status <> 'completed' then
    perform public.notify(
      new.patient_id, 'appointment_completed', 'Appointment completed',
      'Your appointment with Dr. ' || coalesce(doctor_name, '') || ' is marked completed.',
      '/patient/appointments'
    );
  end if;
  return new;
end;
$$;

create trigger trg_appointment_notify
  after insert or update on public.appointments
  for each row execute function public.on_appointment_change();

create or replace function public.on_prescription_created()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  doctor_name text;
begin
  select full_name into doctor_name from public.profiles where id = new.doctor_id;
  perform public.notify(
    new.patient_id, 'prescription_created', 'New prescription',
    'Dr. ' || coalesce(doctor_name, '') || ' added a new prescription for you.',
    '/patient/prescriptions'
  );
  return new;
end;
$$;

create trigger trg_prescription_notify
  after insert on public.prescriptions
  for each row execute function public.on_prescription_created();

create or replace function public.on_medical_record_created()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.notify(
    new.patient_id, 'medical_record_added', 'New medical record',
    'A new ' || new.record_type || ' record was added to your file.',
    '/patient/medical-records'
  );
  return new;
end;
$$;

create trigger trg_medical_record_notify
  after insert on public.medical_records
  for each row execute function public.on_medical_record_created();

create or replace function public.on_medical_report_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    perform public.notify(
      new.patient_id, 'report_uploaded', 'Report uploaded',
      new.report_type || ' has been uploaded to your medical records.',
      '/patient/medical-records'
    );
  elsif tg_op = 'UPDATE' and new.status is distinct from old.status then
    if new.status = 'critical' then
      perform public.notify(
        new.patient_id, 'report_critical', 'Report flagged critical',
        'Your ' || new.report_type || ' has been flagged for urgent review. Please contact your doctor.',
        '/patient/medical-records'
      );
    elsif new.status = 'reviewed' then
      perform public.notify(
        new.patient_id, 'report_reviewed', 'Report reviewed',
        'Your doctor has reviewed your ' || new.report_type || '.',
        '/patient/medical-records'
      );
    end if;
  end if;
  return new;
end;
$$;

create trigger trg_medical_report_notify
  after insert or update on public.medical_reports
  for each row execute function public.on_medical_report_change();

create or replace function public.on_profile_approved()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.approved = true and old.approved = false then
    perform public.notify(
      new.id, 'account_approved', 'Account approved',
      'Your account has been approved. You can now sign in and use FriendlyHealthy.',
      '/' || new.role::text
    );
  end if;
  return new;
end;
$$;

create trigger trg_profile_approved_notify
  after update on public.profiles
  for each row execute function public.on_profile_approved();

create or replace function public.on_billing_created()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.notify(
    new.patient_id, 'bill_created', 'New bill',
    'A new bill of Rs. ' || new.amount || ' has been added to your account.',
    '/patient/billing'
  );
  return new;
end;
$$;

create trigger trg_billing_notify
  after insert on public.billing
  for each row execute function public.on_billing_created();

-- ---------------------------------------------------------------------------
-- messages — direct doctor<->patient messaging, gated to pairs with an
-- established relationship via the same doctor_has_consulted() boundary
-- clinical tables already use.
-- ---------------------------------------------------------------------------

create table public.messages (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null references public.profiles (id),
  recipient_id uuid not null references public.profiles (id),
  body text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index idx_messages_sender on public.messages (sender_id, created_at);
create index idx_messages_recipient on public.messages (recipient_id, created_at);

alter table public.messages enable row level security;

create policy "messages_select_own" on public.messages
  for select using (sender_id = auth.uid() or recipient_id = auth.uid());

create policy "messages_insert_own" on public.messages
  for insert with check (
    sender_id = auth.uid()
    and (
      (public.current_user_role() = 'doctor' and public.doctor_has_consulted(auth.uid(), recipient_id))
      or (public.current_user_role() = 'patient' and public.doctor_has_consulted(recipient_id, auth.uid()))
    )
  );

create policy "messages_update_recipient_read" on public.messages
  for update using (recipient_id = auth.uid());

create or replace function public.on_message_created()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  sender_name text;
  sender_role public.user_role;
begin
  select full_name, role into sender_name, sender_role
  from public.profiles where id = new.sender_id;

  perform public.notify(
    new.recipient_id, 'message_received',
    'New message from ' || coalesce(sender_name, 'someone'),
    left(new.body, 140),
    case when sender_role = 'doctor' then '/patient/messages' else '/doctor/messages' end
  );
  return new;
end;
$$;

create trigger trg_message_notify
  after insert on public.messages
  for each row execute function public.on_message_created();
